### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by tingtingqu** [feevos/resuneta#13]
Hello, I am an academic novice, I don’t understand why there is no train.py and test.py

**Comment by feevos** [comment]
I apologise for this. No other reason than save some time from developing it, because the production training code cannot be open sourced. However, if you are familiar with mxnet, it is straightforward to write single or multi-gpu training and testing code. And you have - through this repository - all algorithms that we used for our manuscript. 

Regards

**Comment by tingtingqu** [comment]
Thank you very much. I already know the problem------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月1日(星期三) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [feevos/resuneta] train.py (#13)
