### ISSUE TITLE
How to set the IDs in the src/chopchop_run.py file?

### ISSUE THREAD

**Issue by simonep1052** [feevos/resuneta#17]
Hello, could you give me a hint or a short explanation on how to set [IDs](https://github.com/feevos/resuneta/blob/master/src/chopchop_run.py#L46) please?

**Comment by feevos** [comment]
Hi @simonep1052  could you please elaborate on what is that you don't understand? It's been a long time since I did this code, I think IDs are the tile names like 2_13, 2_14 etc. I am basically stripping the other characters from the filename.  If you run the code only on this part you should be able to verify ;). Let me know how you go. 

Cheers

**Comment by simonep1052** [comment]
Thank you very much for your time and reply. I figured that I did not set directory path well so IDs was an empty list. Now, `chopchop_run.py` goes well.

**Comment by feevos** [comment]
happy I could be of some help :) If you have further questions I'll try my best to help, please do not hesitate to post a question here. Closing this now

Cheers
